[package]
name = "gateway"
version = "0.0.0"
edition = "2021"

[dependencies]
mockall = "0.11.0"
mockall_double = "0.3.0"

# Internal
driver = { path = "../driver" }
usecase = { path = "../usecase" }
domain = { path = "../domain" }
